title:              zenoengine's blog
tagline:            zenoengine
description:        zenoengine's blog
url:                http://zenoengine.github.io

author:
  name:             zenoengine
  url:
  email:

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
paginate-path:      "/page:lang/page:num/"
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

plugins:
    - jekyll-feed
